# Generated by Django 3.2.9 on 2021-11-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', related_query_name='project_entry', to='projects.Category', verbose_name='Категории'),
        ),
    ]
