# Generated by Django 3.2.9 on 2021-11-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgallery',
            options={'verbose_name': 'Галерея проекта', 'verbose_name_plural': 'Галереи проектов'},
        ),
    ]
