# Generated by Django 3.2.9 on 2021-11-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
    ]
