# Generated by Django 3.2.9 on 2021-12-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectgallery_videoyoutube'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='presentation',
            field=models.FileField(default='', upload_to='uploads/', verbose_name='Презентация'),
            preserve_default=False,
        ),
    ]
