# Generated by Django 3.2.9 on 2021-11-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='tes',
        ),
    ]
