# Generated by Django 3.2.9 on 2021-11-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_remove_faq_tes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=64, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=32, verbose_name='Номер телефона клиента')),
                ('order_type', models.CharField(max_length=32, verbose_name='Тип заказа')),
                ('distance_to_sea', models.IntegerField(blank=True, null=True, verbose_name='Расстояние до моря')),
                ('profit_assessment', models.SmallIntegerField(blank=True, choices=[(None, 'Выберите уровень важности'), (1, 'Важность первого уровня'), (2, 'Важность второго уровня'), (3, 'Важность третьего уровня'), (4, 'Важность четвертого уровня'), (5, 'Важность пятого уровня')], null=True, verbose_name='Важность доходности')),
                ('assessment_district', models.SmallIntegerField(blank=True, choices=[(None, 'Выберите уровень важности'), (1, 'Важность первого уровня'), (2, 'Важность второго уровня'), (3, 'Важность третьего уровня'), (4, 'Важность четвертого уровня'), (5, 'Важность пятого уровня')], null=True, verbose_name='Важность района')),
                ('assessment_distance_to_sea', models.SmallIntegerField(blank=True, choices=[(None, 'Выберите уровень важности'), (1, 'Важность первого уровня'), (2, 'Важность второго уровня'), (3, 'Важность третьего уровня'), (4, 'Важность четвертого уровня'), (5, 'Важность пятого уровня')], null=True, verbose_name='Важность расстояния до моря')),
                ('rental_period', models.SmallIntegerField(blank=True, null=True, verbose_name='Срок аренды')),
                ('budget', models.SmallIntegerField(blank=True, choices=[(None, 'ВЫберите предполагаемый бюджет'), (1, 'от $300.000'), (2, '$200.000-$500.000'), (3, '$500.000-$1.000.000'), (4, '$1.000.000-$3.000.000'), (5, 'Более $3.000.000')], null=True, verbose_name='Планируемый бюджет')),
            ],
        ),
    ]
