# Generated by Django 3.2.9 on 2021-11-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20211124_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='villa_area',
            field=models.CharField(blank=True, choices=[('R1', '1 спальня'), ('R2', '2 спальни'), ('R3', '3 спальни'), ('R4', '4 спальни и больше')], max_length=8, null=True, verbose_name='Площадь виллы'),
        ),
    ]
