# Generated by Django 3.2.9 on 2021-11-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='order_type',
            field=models.IntegerField(max_length=32, verbose_name='Тип заказа'),
        ),
    ]
