# Generated by Django 3.2.9 on 2021-11-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_auto_20211118_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='assessment_distance_to_sea',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Данные отсутствуют'), (1, 'Первый уровень'), (2, 'Второй уровень'), (3, 'Третий уровень'), (4, 'Четвертый уровень'), (5, 'Пятый уровень')], null=True, verbose_name='Важность расстояния до моря'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='assessment_district',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Данные отсутствуют'), (1, 'Первый уровень'), (2, 'Второй уровень'), (3, 'Третий уровень'), (4, 'Четвертый уровень'), (5, 'Пятый уровень')], null=True, verbose_name='Важность района'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='budget',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Данные отсутствуют'), (1, 'от $300.000'), (2, '$200.000 - $500.000'), (3, '$500.000 - $1.000.000'), (4, '$1.000.000 - $3.000.000'), (5, 'Более $3.000.000')], null=True, verbose_name='Планируемый бюджет'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='profit_assessment',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Данные отсутствуют'), (1, 'Первый уровень'), (2, 'Второй уровень'), (3, 'Третий уровень'), (4, 'Четвертый уровень'), (5, 'Пятый уровень')], null=True, verbose_name='Важность доходности'),
        ),
    ]
