# Generated by Django 3.2.9 on 2021-11-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_auto_20211118_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.SmallIntegerField(help_text='Чем больше значение, тем важнее будет категория при отборе проектов в рекомендациях', verbose_name='Вес категории'),
        ),
    ]
