# Generated by Django 3.2.9 on 2021-11-19 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_auto_20211119_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='assessment_distance_to_sea',
            field=models.CharField(blank=True, choices=[('L1', 'Первый уровень'), ('L2', 'Второй уровень'), ('L3', 'Третий уровень'), ('L4', 'Четвертый уровень'), ('L5', 'Пятый уровень')], max_length=8, null=True, verbose_name='Важность расстояния до моря'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='assessment_district',
            field=models.CharField(blank=True, choices=[('L1', 'Первый уровень'), ('L2', 'Второй уровень'), ('L3', 'Третий уровень'), ('L4', 'Четвертый уровень'), ('L5', 'Пятый уровень')], max_length=8, null=True, verbose_name='Важность района'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='budget',
            field=models.CharField(blank=True, choices=[('B1', 'от $300.000'), ('B2', '$200.000 - $500.000'), ('B3', '$500.000 - $1.000.000'), ('B4', '$1.000.000 - $3.000.000'), ('B5', 'Более $3.000.000')], max_length=8, null=True, verbose_name='Планируемый бюджет'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='distance_to_sea',
            field=models.CharField(blank=True, choices=[('M5', '5 минут'), ('M10', '10 минут'), ('M15', 'от 15 минут')], max_length=8, null=True, verbose_name='Расстояние до моря'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='order_type',
            field=models.CharField(choices=[('R', 'Аренда вилл'), ('C', 'Строительство')], max_length=8, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='profit_assessment',
            field=models.CharField(blank=True, choices=[('L1', 'Первый уровень'), ('L2', 'Второй уровень'), ('L3', 'Третий уровень'), ('L4', 'Четвертый уровень'), ('L5', 'Пятый уровень')], max_length=8, null=True, verbose_name='Важность доходности'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='rental_period',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)], verbose_name='Срок аренды'),
        ),
    ]
