# Generated by Django 3.2.9 on 2021-11-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_projectgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(null=True, upload_to='sys/projects/', verbose_name='Главное изображение'),
        ),
    ]
